# Generated by Django 5.2.5 on 2025-09-03 13:40

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='features',
            field=wagtail.fields.StreamField([('feature', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 1: ('wagtail.blocks.TextBlock', (), {}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Font Awesome Icon Name', 'max_length': 50}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('icon', 2)]], {})}),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.CharField(blank=True, help_text='Untertitel für die Homepage', max_length=300),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(blank=True, help_text='Haupttitel für die Homepage', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='Einführungstext'),
        ),
    ]
