# Generated by Django 5.2.5 on 2025-09-03 14:06

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homepage_features_homepage_hero_image_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='offer_background_image',
            field=models.ForeignKey(blank=True, help_text='Hintergrundbild für die Angebots-Section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='offer_cta_text',
            field=models.CharField(blank=True, default='Jetzt buchen', help_text='Text für Call-to-Action Button', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='offer_cta_url',
            field=models.URLField(blank=True, help_text='Link für CTA Button'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='offer_description',
            field=wagtail.fields.RichTextField(blank=True, help_text='Beschreibung des Angebots'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='offer_title',
            field=models.CharField(blank=True, help_text="z.B. 'Herbst-Special'", max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='offer_valid_until',
            field=models.DateField(blank=True, help_text='Gültig bis (optional)', null=True),
        ),
    ]
